#!/usr/bin/env python

"""
A management script which contains subcommands useful for administration.

It can be invoked from project root with './manage [subcommand]'. For more
information try './manage --help'.

:copyright: (c) 2016 Pinn Technologies, Inc.
:license: All rights reserved
"""

import click
import management


@click.group()
def manage():
    pass

# Add subcommands
manage.add_command(management.install)  # NOQA
manage.add_command(management.shell)  # NOQA
manage.add_command(management.unit_tests)  # NOQA


if __name__ == '__main__':
    manage()
